### ISSUE TITLE
Cannot find name 'Collections' even with j4ts dependency

### ISSUE THREAD

**Issue by lalalic** [cincheo/jsweet#708]
I'm working on 1.8JDK, 3.0.0 jsweet on Mac, I have a very simple java class as following:
import java.util.Collections;

public final class Test {

	public static int test(){
		Collections.unmodifiableMap(null);
		return 1;
	}
}

and pom.xml looks like:
```
<project>
...
	<dependencies>
		<dependency>
			<groupId>org.jsweet</groupId>
			<artifactId>jsweet-core</artifactId>
			<version>${jsweet.core.version}</version>
		</dependency>
		<dependency>
			<groupId>org.jsweet</groupId>
			<artifactId>j4ts</artifactId>
			<version>2.0.0</version>
		</dependency>
	</dependencies>
</project>
```
JDK is 1.8, jsweet is 3.0.0, then I got error Cannot find name 'Collections':
the following ts created:
```
/* Generated from Java with JSweet 3.0.0 - http://www.jsweet.org */
export class Test {
    public static test(): number {
        Collections.unmodifiableMap<any, any>(null);
        return 1;
    }
}
Test["__class"] = "Test";
```
the log is as following:
```
2021-10-25 20:58:39.039 ERROR output:55 - [ts] Cannot find name 'Collections'. at /Users/lir/Workspace/jsweet-quickstart/src/main/java/com/docscience/pathfinder/font/Test.java(8)
2021-10-25 20:58:39.039 INFO  JSweetTranspiler:834 - transpilation process finished in 3059 ms 
> java2ts: 710.940533ms
> ts2js: 2286.094849ms

[ERROR] transpilation failed
org.apache.maven.plugin.MojoFailureException: transpilation failed with 1 error(s) and 0 warning(s)

=========================================
TRANSPILATION ERRORS SUMMARY:
* /Users/xxx/Workspace/jsweet-quickstart/src/main/java/Test.java(8,45)[ts] Cannot find name 'Collections'.


=========================================
    at org.jsweet.AbstractJSweetMojo.transpile (AbstractJSweetMojo.java:694)
    at org.jsweet.JSweetMojo.execute (JSweetMojo.java:43)
...
```
Am I missing something?

thanks
