### ISSUE TITLE
Array iterator fails

### ISSUE THREAD

**Issue by thomasAtToem** [cincheo/jsweet#623]
Simple java iterations with arrays like
        Object[] log = ...;  
        for (Object l:log)
            System.out.print(" ;" + String.valueOf(l));
fail in jsweet 3 (but works in jsweet 2) with 

2020-09-09 10:38:36.036 INFO  TypeScript2JavaScriptWithTscTranspiler:90 - bundle.ts(287,34): error TS2339: Property 'iterator' does not exist on type 'any[]'.
2020-09-09 10:38:36.036 ERROR output:55 - property 'iterator' does not exist on type 'any[]' at /home/thomas/Workspaces/impulse/de.toem.impulse.web.frontend/build/jsweet/src/main/java/de/toem/basics/core/Utils.java(340)

**Comment by lgrignon** [comment]
Hello, which version of JSweet 3 are you using please ,

**Comment by lgrignon** [comment]
3.0.0-RC4 is out since yesterday

**Comment by thomasAtToem** [comment]
ITs working with 3.0.0-RC4 (failed with RC3).
Thanks !!
