### ISSUE TITLE
Issue when enum implements an interface

### ISSUE THREAD

**Issue by enricostara** [cincheo/jsweet#329]
Hi,

if you pass (as argument) an enum (ex EnumType) that implements an interface (ex InterfaceType) and such argument is declared as the interface type, transpiler throws the following error:

JSweetTranspiler:1363 - bundle.ts(row,col): error TS2345: Argument of type 'EnumType' is not assignable to parameter of type 'InterfaceType'.

Best,
E

**Comment by renaudpawlak** [comment]
It should be quite easy to fix (easy enough to fix it for v2 I think). Here is my test case (please make sure it entails your issue):

```java
public class EnumsImplementingInterfaces {
	public static void main(String[] args) {
		assert 2 == new EnumsImplementingInterfaces().m(E.B);
	}
	int m(I i) {
		return i.m();
	}
}

interface I {
	int m();
}

enum E implements I {
	A, B, C;
	@Override
	public int m() {
		return ordinal() + 1;
	}
}
```

**Comment by enricostara** [comment]
Yes, it's exactly the issue :)

I temporarily switched my enum type to class type (as work-around) in order to implement the interface.

I'm currently working with jsweet 2.0.0-snapshot, therefor should I already find the fix refreshing maven?...

Thanks for your prompt support, the project is really big and ambitious!!

**Comment by renaudpawlak** [comment]
Yes. I will push ASAP. It should close the issue when fixed.

**Comment by enricostara** [comment]
Amazing! thanks 👍
