### ISSUE TITLE
Some missing javaemul methods used in translation when j4ts omitted

### ISSUE THREAD

**Issue by chrismiddleton** [cincheo/jsweet#262]
The following are used in the code:

    javaemul.internal.CharacterHelper.isDigit
    javaemul.internal.CharacterHelper.isLetterOrDigit
    javaemul.internal.CharacterHelper.toLowerCase
    javaemul.internal.CharacterHelper.toUpperCase
    javaemul.internal.DoubleHelper.doubleToLongBits
    javaemul.internal.DoubleHelper.longBitsToDouble
    javaemul.internal.FloatHelper.floatToIntBits
    javaemul.internal.FloatHelper.intBitsToFloat
    javaemul.internal.IntegerHelper.rotateLeft
    javaemul.internal.IntegerHelper.toHexString

but are not present so cause errors in the compile using 2.0.0-SNAPSHOT. I'm guessing that one way I could work around for now is to make those classes myself (but didn't try yet).

**Comment by renaudpawlak** [comment]
Many methods are not supported yet internally by JSweet. They will eventually be supported but in the meantime, what you can do is to declare these classes/methods so that your program can use them (even if not supported directly by JSweet).

With JSweet 2, all you need to do is to create definitions (``def.libname.*`` classes). For example:

```java
package def.runtime.javaemul.internal;
public class CharacterHelper {
  // all the methods you need to compile your program (as native methods)
   public static native boolean isDigit();
   ...
```

This should solve your compilation errors (here I call the external lib "runtime" but actually the name does not matter). Then, you will need to have the J4TS JavaScript bundle to run your program, of course.

**Comment by chrismiddleton** [comment]
Thanks for your help. I will do that for now.

**Comment by renaudpawlak** [comment]
FYI, I have just added support for:

Double.doubleToLongBits
Double.longBitsToDouble
Float.floatToIntBits
Float.intBitsToFloat

So you should not need the associated helpers (plus I think that these methods are buggy in the current J4TS implementation).

**Comment by renaudpawlak** [comment]
Also added all the support for Character.
RotateLeft is still missing.

**Comment by chrismiddleton** [comment]
Thanks, Renaud, for all your hard work!

**Comment by renaudpawlak** [comment]
I guess that's will be enough by default. I have documented how to write JSweet extension, so people should be able to support these be themselves now... https://github.com/cincheo/jsweet/blob/master/doc/jsweet-language-specifications.md#extending-the-transpiler
