### ISSUE TITLE
JSweet 2.0 + J4TS 4.0?

### ISSUE THREAD

**Issue by alievrenkut** [cincheo/jsweet#225]
Hi,
I tried to upgrade my project JSweet project to 1.2.0-SNAPSHOT to 2.0.0-SNAPSHOT. I could build without error by maven before but now I got a lot of errors. I am guessing my problems come from using J4TS. Is there a version of J4TS works for JSweet 2.0?

Some of errors I got:
error TS1046: A 'declare' modifier is required for top level declaration in a .d.ts file.
error TS1039: Initializers are not allowed in ambient contexts.

I build with bundle option.

**Comment by renaudpawlak** [comment]
Umm... it is a little early to migrate to JSweet 2.0 with J4TS, but from your errors, I suspect that you have another problem than just using J4TS.
One first fundamental thing with JSweet 2.0 is that you don't need J4TS anymore for most basic Java APIs. So you should first try to remove J4TS from your dependencies and see what happens.

**Comment by alievrenkut** [comment]
I will wait then because I used J4TS while porting an library which has 400+ classes. Everything works with 1.2 so I can wait. I really wanted to try AddPrefixToNonPublicMembersAdapter :-)
